/**
 * See description in the post actionTypes.js file
 */

export const FETCH_ALL_CATEGORIES_REQUESTED = 'FETCH_ALL_CATEGORIES_REQUESTED'
export const FETCH_ALL_CATEGORIES_START = 'FETCH_ALL_CATEGORIES_START'
export const FETCH_ALL_CATEGORIES_SUCCESS = 'FETCH_ALL_CATEGORIES_SUCCESS'
export const FETCH_ALL_CATEGORIES_FAILED = 'FETCH_ALL_CATEGORIES_FAILED'